### ISSUE TITLE
Make Node a Template

### ISSUE THREAD

**Issue by ColtenMikulastik** [ColtenMikulastik/DataStrucCPP#6]

**Comment by nitish312** [comment]
Hey, could you please describe for which data structure you want to create a node template? 
Is it linked list node or tree node?
Please assign me this task and I will work on this issue.

**Comment by ColtenMikulastik** [comment]
oh yeah! I was thinking that a node object that has an dynamic array of pointers to other nodes, and a template data type that could store anything you want. The plan was to make this object as robust as possible for any data structure. I started the code in "NodeTemplate".

**Comment by ColtenMikulastik** [comment]
Great job! Thanks for your help
